version: 1

loggers:
  root:
    level: DEBUG
    handlers: [console]
  aioms.access:
    level: INFO
    handlers: [access]
    propagate: no
  aioms.application:
    level: INFO
    handlers: [application]
    propagate: no
  aioms.general:
    level: INFO
    handlers: [console, general]
    propagate: no

formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(thread)d - %(filename)s:%(lineno)d - %(message)s'
  timedRotating:
    format: '%(asctime)s - %(levelname)s - %(thread)d - %(filename)s:%(lineno)d  %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  access:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'logs/aioms.access.log'
    maxBytes: 209715200  # 200 * 1024 * 1024
    backupCount: 5

  application:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'logs/aioms.application.log'
    maxBytes: 204800
    backupCount: 5

  general:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'logs/aioms.gen.log'
    maxBytes: 204800
    backupCount: 5